apiVersion: v1
kind: ConfigMap
metadata:
  name: library-config
  namespace: library
data:
  MYSQL_DATABASE: library_db
  MYSQL_USER: appuser
  DB_HOST: mysql
  DB_PORT: "3306"
  JWT_EXPIRE_MIN: "1440"

