apiVersion: v1
kind: Secret
metadata:
  name: library-secret
  namespace: library
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_PASSWORD: Ankit261
  JWT_SECRET: 2a0cb3802d88cefaab7d64b2623c2fe0fe33146de84d0dcfee3e61e8eaf295f1

